### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by gemesa** [RoseSecurity-Research/Active-Projects#1]
There are some broken links in the readme, for example
- https://github.com/RoseSecurity-Research/Blue-Teaming-TTPs
- https://github.com/RoseSecurity-Research/GasPot

**Comment by RoseSecurity** [comment]
@gemesa Thank you for checking out our projects! These two specific projects are for internal collaboration and are currently private repositories before public release. If you would like to support either of these projects, feel free to respond on this thread and I can add you to them.

**Comment by gemesa** [comment]
Im interested, please add me

**Comment by RoseSecurity** [comment]
Added!
